### PR TITLE
Add modules

### LINKED ISSUE #3: Users can't specify additional modules
Duplicates [this issue](https://github.com/OSC/bc_osc_rstudio_server/issues/28) on the regular rstudio repo.

### PR DESCRIPTION
**Pull request by johrstrom**
Add modules to resolve #3 and to load texlive so users can edit Markdown R files (texlive also adds parity with owens rstudio app).

### CODE REVIEW

**Comment by ericfranz** [comment]
Shameema should comment on this. I don't recall her GitHub handle so I'll send an email.

This is also a good example of something ideally we would be providing server side validation on. Just taking the text as is that the user inserts and embedding it in the bash script is not preferable. Though I'm sure there are other places where we do this exact thing. I'm also not sure what type of validation, exactly, we might do.

Maybe minimally in cases like these we should start using https://ruby-doc.org/stdlib-2.5.1/libdoc/shellwords/rdoc/Shellwords.html to escape the string, if we aren't doing validation in some other way? Happy to discuss.

**Comment by ericfranz** [comment]
@johrstrom Is there a releated INCIDENT? Are multiple users requesting this feature? Also, just to capture on the PR what I mentioned in an email, my concern about this approach is it is easy to mistype a module name, or not realize that in order to load a module you need another module, and you won’t know about the error till the job starts. Though I imagine the error will be logged and the RStudio session will start anyways, just without the module loaded.

When we first introduced web forms for launching interactive apps, we had decided against providing such free form text inputs to augment the job script as a result.

**Comment by johrstrom** [comment]
Module roles right past that error, and since it's on a new line it's already loaded everything else fine. Then Rstudio boots up, just without the additional modules.  (note that if you did `module load goodmodule badmodule` it wouldn't load either good or bad). The error I tested with is given below.

As to validation, I'm happy to add it, though we don't actually know what modules exist on the web server and we've had issues ssh-ing during templating.  We can also escape things, but I'm not sure any modules have quotes. 

This PR is a duplicate of [this one](https://github.com/OSC/bc_osc_rstudio_server/pull/29). and the originating issue is [this one](https://github.com/OSC/bc_osc_rstudio_server/issues/28).

```text
Lmod has detected the following error: The following module(s) are unknown:
"sadfsadfasdfsgd"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "sadfsadfasdfsgd"

Also make sure that all modulefiles written in TCL start with the string
#%Module




Currently Loaded Modules:
  1) xalt/latest    4) R/3.6.1                     7) texlive/2018
  2) gnu/9.1.0      5) rstudio/1.1.380_server
  3) mkl/2019.0.3   6) rstudio_container/2019Feb
```

**Comment by johrstrom** [comment]
@soottikkal and @ZQyou FYI.

**Comment by ZQyou** [comment]
@johrstrom  @ericfranz  Thank you. We can talk over this in Monday meeting.

**Comment by johrstrom** [comment]
Closing this PR as we're coming up with a stronger strategy around viewing module output and determining dependencies. Please use [this enhancement ticket](https://github.com/OSC/bc_osc_rstudio_server/issues/28) for any discussion on the feature if there's no open PR.

**Pull request closed without merging**
